name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      id: node_version
      run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)  

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ steps.node_version.outputs.NODE_VERSION }}
        
    - run: npm install
    - run: npm run lint
    - run: npm test
